### ISSUE TITLE
Suggestion: Can we migrate the CSS Framework?

### ISSUE THREAD

**Issue by unRARed** [bwentzloff/afs#107]
While Bootstrap is nice to get something up and running quickly, it's not the most maintainable and usually turns into a lot of overly specific CSS and `important!` before too long. I've had success with [Blaze UI](https://www.blazeui.com/), but it's not heavily used. I think [Material Design Lite](https://getmdl.io/) would be a good option. My reasoning is that it's got a clean modern-ish UI and has an Android-like appearance. I would also expect most usage to be coming from phones while users are watching the games. Thoughts?

**Comment by bwentzloff** [comment]
As I’m sure you can tell, I’m not much of a front end dev, so I’m open to suggestions. Sounds like that would be a pretty massive overhaul though, because I’m using Bootstrap-Vue so it’s all kind of integrated together.

**Comment by unRARed** [comment]
Ahh, yes, that does complicate things a bit. I could try playing around [with this](https://vuematerial.io/components/app) on a different branch.

**Comment by kenjdavidson** [comment]
Not that my opinion matters, but a higher priority for th ui should be splitting the league page into sub routes so that each page can be maintained more easily. Ie.

/league/:id/
/league/:id/rosters
/league/:id/matchups
 
Etc.

I got the environment setup last week and was going to run through this on my flight, but my son didn't accommodate.
